// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsqrudrndmrcwersvlrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zcXJ1ZHJuZG1yY3dlcnN2bHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTc4NDMsImV4cCI6MjA3MTQzMzg0M30.R4Y2jVqEmwP3QxNNUhM_KodRYKMjuNFIEJAyk-dvUiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});